PROFILE = {
    "name": "Amir",
    "age": 34,
    "height_cm": 185,
    "start_weight_lb": 233.0,
    "target_weight_lb": 213.0,
    "experience": "Intermediate",
    "sessions_per_week": 3,
    "session_minutes": 45,
    "goals": "Build muscle, improve consistency, track bodyweight and progress",
    "constraints": "Keep sessions efficient, machine-focused and easy to log.",
}

EXERCISES = [
    ("Lat Pulldown", "Back", "Machine/Cable", "Chest tall; pull elbows down without swinging."),
    ("Seated Row Machine", "Back", "Machine", "Keep torso still and squeeze the shoulder blades."),
    ("High Row Machine", "Back", "Machine", "Drive elbows back and keep the chest supported where available."),
    ("Preacher Curl Machine", "Biceps", "Machine", "Keep upper arms planted and control the lowering phase."),
    ("Cable Curl", "Biceps", "Cable", "Keep elbows close to your sides; avoid body swing."),
    ("Dumbbell Hammer Curl", "Biceps", "Dumbbell", "Neutral grip; keep shoulders relaxed."),
    ("Machine Chest Press", "Chest", "Machine", "Set the seat so handles sit around mid-chest; control each rep."),
    ("Incline Chest Press Machine", "Chest", "Machine", "Keep shoulder blades supported and avoid bouncing."),
    ("Pec Deck", "Chest", "Machine", "Use a comfortable stretch and squeeze the chest together."),
    ("Rope Tricep Pushdown", "Triceps", "Cable", "Keep elbows pinned and finish each rep fully."),
    ("Overhead Cable Tricep Extension", "Triceps", "Cable", "Brace the torso and keep elbows pointing forward."),
    ("Assisted Dip Machine", "Triceps", "Machine", "Use a controlled depth and keep shoulders comfortable."),
    ("Machine Shoulder Press", "Shoulders", "Machine", "Keep back supported and press without shrugging."),
    ("Lateral Raise Machine", "Shoulders", "Machine", "Lead with the elbows; stop around shoulder height."),
    ("Leg Press", "Legs", "Machine", "Keep hips and back supported; use a controlled pain-free depth."),
    ("Leg Extension", "Quads", "Machine", "Pause briefly at the top and lower under control."),
    ("Seated Leg Curl", "Hamstrings", "Machine", "Keep hips down and squeeze at the bottom."),
    ("Calf Raise Machine", "Calves", "Machine", "Full comfortable range; pause at the top and bottom."),
    ("Cable Face Pull", "Shoulders", "Cable", "Pull toward eye level with elbows high and controlled."),
    ("Incline Dumbbell Press", "Chest", "Dumbbell", "Keep shoulder blades set and use a stable bench angle."),
    ("Chest-Supported Dumbbell Row", "Back", "Dumbbell", "Use bench support and avoid momentum."),
]

PLAN = [
    ("Back + Biceps", 1, "Lat Pulldown", 3, "8–12", "A"),
    ("Back + Biceps", 2, "Seated Row Machine", 3, "8–12", "B"),
    ("Back + Biceps", 3, "High Row Machine", 3, "10–12", "C"),
    ("Back + Biceps", 4, "Preacher Curl Machine", 3, "10–12", "D"),
    ("Back + Biceps", 5, "Cable Curl", 3, "10–12", "E"),
    ("Back + Biceps", 6, "Dumbbell Hammer Curl", 2, "10–12", "F"),
    ("Chest + Triceps", 1, "Machine Chest Press", 3, "8–12", "A"),
    ("Chest + Triceps", 2, "Incline Chest Press Machine", 3, "8–12", "B"),
    ("Chest + Triceps", 3, "Pec Deck", 3, "10–15", "C"),
    ("Chest + Triceps", 4, "Rope Tricep Pushdown", 3, "10–12", "D"),
    ("Chest + Triceps", 5, "Overhead Cable Tricep Extension", 3, "10–12", "E"),
    ("Chest + Triceps", 6, "Assisted Dip Machine", 2, "8–12", "F"),
    ("Shoulders + Legs", 1, "Machine Shoulder Press", 3, "8–12", "A"),
    ("Shoulders + Legs", 2, "Lateral Raise Machine", 3, "10–15", "B"),
    ("Shoulders + Legs", 3, "Leg Press", 3, "8–12", "C"),
    ("Shoulders + Legs", 4, "Leg Extension", 3, "10–15", "D"),
    ("Shoulders + Legs", 5, "Seated Leg Curl", 3, "10–15", "E"),
    ("Shoulders + Legs", 6, "Calf Raise Machine", 3, "12–15", "F"),
]
