PROFILE = {
    "name": "Amir",
    "age": 34,
    "height_cm": 185,
    "start_weight_lb": 233.0,
    "target_weight_lb": 213.0,
    "experience": "Intermediate–advanced",
    "sessions_per_week": 3,
    "session_minutes": 45,
    "goals": "Build muscle; reduce back pain; improve posture; lose body fat",
    "constraints": "Back symptoms (diagnosis not confirmed), knee swelling, current neck sprain. Avoid loaded bending, squats, deadlifts, running and painful movements.",
}

EXERCISES = [
    ("Leg Press", "Legs", "Machine", "Keep back supported; use a pain-free depth."),
    ("Machine Chest Press", "Chest", "Machine", "Keep ribs down and neck neutral."),
    ("Cable Lateral Raise", "Shoulders", "Cable", "Light, controlled range."),
    ("Incline Dumbbell Press", "Chest", "Dumbbell", "Bench supported; avoid excessive arch."),
    ("Rope Tricep Pushdown", "Arms", "Cable", "Keep torso still."),
    ("Press-up", "Chest", "Bodyweight", "Elevate hands if needed; stop if back or neck symptoms rise."),
    ("Chest-Supported Row", "Back", "Machine", "Maintain chest support throughout."),
    ("Lat Pulldown", "Back", "Cable", "Pull to upper chest without leaning back."),
    ("Face Pull", "Shoulders", "Cable", "Use a light load and neutral neck."),
    ("Seated Cable Row", "Back", "Cable", "Upright torso; no rocking."),
    ("Hammer Curl", "Arms", "Dumbbell", "Seated if preferred."),
    ("Seated Hamstring Curl", "Legs", "Machine", "Controlled tempo."),
    ("Pec Deck", "Chest", "Machine", "Keep shoulders comfortable."),
    ("Assisted Pull-up", "Back", "Machine", "Use pulldown if neck is irritated."),
    ("Machine Shoulder Press", "Shoulders", "Machine", "Light only; omit if neck or back symptoms increase."),
    ("Incline Dumbbell Curl", "Arms", "Dumbbell", "Keep shoulders against bench."),
    ("Cable Fly", "Chest", "Cable", "Split stance; light and controlled."),
    ("Sit-up", "Core", "Bodyweight", "Bodyweight, controlled and symptom-free only."),
    ("Bird Dog", "Core", "Bodyweight", "Keep spine still."),
    ("Side Plank", "Core", "Bodyweight", "Use knees-down regression if needed."),
    ("Dead Bug", "Core", "Bodyweight", "Keep lower back controlled."),
    ("Glute Bridge", "Glutes", "Bodyweight", "Stop before back extension."),
    ("Reverse Crunch", "Core", "Bodyweight", "Small, controlled range."),
    ("Pallof Press", "Core", "Cable", "Resist rotation."),
]

# day, order, exercise, sets, reps, superset label
PLAN = [
    ("Monday · Push + Quads", 1, "Leg Press", 4, "8–10", "A"),
    ("Monday · Push + Quads", 2, "Machine Chest Press", 3, "10–12", "B1"),
    ("Monday · Push + Quads", 3, "Cable Lateral Raise", 3, "12–15", "B2"),
    ("Monday · Push + Quads", 4, "Incline Dumbbell Press", 3, "10", "C1"),
    ("Monday · Push + Quads", 5, "Rope Tricep Pushdown", 3, "12", "C2"),
    ("Monday · Push + Quads", 6, "Press-up", 2, "Technical AMRAP", "D"),
    ("Wednesday · Pull", 1, "Chest-Supported Row", 4, "8–10", "A"),
    ("Wednesday · Pull", 2, "Lat Pulldown", 3, "10", "B1"),
    ("Wednesday · Pull", 3, "Face Pull", 3, "15", "B2"),
    ("Wednesday · Pull", 4, "Seated Cable Row", 3, "12", "C1"),
    ("Wednesday · Pull", 5, "Hammer Curl", 3, "12", "C2"),
    ("Wednesday · Pull", 6, "Seated Hamstring Curl", 3, "12", "D"),
    ("Friday · Hybrid", 1, "Leg Press", 3, "15", "A"),
    ("Friday · Hybrid", 2, "Pec Deck", 3, "12", "B1"),
    ("Friday · Hybrid", 3, "Lat Pulldown", 3, "10", "B2"),
    ("Friday · Hybrid", 4, "Machine Shoulder Press", 3, "10", "C1"),
    ("Friday · Hybrid", 5, "Incline Dumbbell Curl", 3, "12", "C2"),
    ("Friday · Hybrid", 6, "Cable Fly", 2, "15", "D1"),
    ("Friday · Hybrid", 7, "Press-up", 2, "Technical AMRAP", "D2"),
    ("Optional · Core + Mobility", 1, "Sit-up", 3, "15", "A1"),
    ("Optional · Core + Mobility", 2, "Bird Dog", 3, "10/side", "A2"),
    ("Optional · Core + Mobility", 3, "Side Plank", 3, "30 sec/side", "A3"),
    ("Optional · Core + Mobility", 4, "Dead Bug", 3, "10/side", "B1"),
    ("Optional · Core + Mobility", 5, "Glute Bridge", 3, "15", "B2"),
    ("Optional · Core + Mobility", 6, "Reverse Crunch", 3, "12", "B3"),
    ("Optional · Core + Mobility", 7, "Pallof Press", 3, "12/side", "C"),
]

